# Generated by Django 3.1.5 on 2021-01-18 21:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_auto_20210118_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('rich_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('section', models.CharField(choices=[('Sci Fi Classics', 'Sci Fi'), ('Literary Classics', 'Literary'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50)),
                ('mood', models.CharField(choices=[('Pure escapism', 'Escapism'), ('Scary', 'Scary'), ('Tense', 'Tense'), ('Laugh out loud', 'Funny'), ('Rollercoaster', 'Rollercoaster'), ('Hard to say', 'Hard To Say')], default='Hard to say', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('free_version_available', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('file_pdf_etc', models.FileField(blank=True, null=True, upload_to='files')),
                ('is_published', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_by_author', to='authors.author')),
            ],
        ),
    ]
