# Generated by Django 3.1.5 on 2021-01-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mood',
            field=models.CharField(choices=[('Pure escapism', 'Pure Escapism'), ('Scary', 'Scary'), ('Tense', 'Tense'), ('Laugh out loud', 'Laugh Out Loud'), ('Rollercoaster', 'Rollercoaster'), ('Hard to say', 'Hard To Say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(choices=[('Sci Fi Classics', 'Sci Fi Classics'), ('Literary Classics', 'Literary Classics'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
